### ISSUE TITLE
is_writable and soft link to a readonly config file

### ISSUE THREAD

**Issue by Takika** [roundcube/plugin-installer#9]
In https://github.com/roundcube/plugin-installer/blob/master/src/Roundcube/Composer/PluginInstaller.php#L50 config file write is tested with is_writable function.
I have these files:
lrwxr-xr-x  1 root  www     16 Dec 15 15:52 config/config.inc.php -> defaults.inc.php
-r--r--r--  1 www   www  45293 Oct 16 01:53 config/defaults.inc.php

I got the 'Do you want to activate the plugin ... ' question.

**Comment by thomascube** [comment]
`is_writable()` is a PHP core function and therefore it's beyond our reach to change any faulty behavior. The method `rcubeConfigFile()` already uses `realpath()` which resolves the symlink to the actual path. Why this is still considered writeable I cannot tell.

Anyway, you should not symlink defaults.inc.php to config.inc.php. That's not the way to do it.
If your local config doesn't differ from the defaults, just keep an empty array in config.inc.php. In order to activate plugins you likely need to alter the config file and modifying the defaults file is a no no!
